esphome:
  name: ld2410s
  friendly_name: LD2410s

external_components:
  - source:
      type: git
      url: https://github.com/MrUndead1996/ld2410s-esphome
      ref: main
    components: [ld2410s]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ld2410S Fallback Hotspot"
    password: "xxx"

captive_portal:

web_server:
  port: 80
  
uart:
  id: uart_bus
  tx_pin: GPIO19
  rx_pin: GPIO23
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

ld2410s:
  uart_id: uart_bus

binary_sensor:
  - platform: ld2410s
    has_target:
      name: Presence
    has_threshold_update:
      name: Threshold update running

sensor:
  - platform: ld2410s
    target_distance:
      name : Target Distance
    threshold_update: 
      name: Threshold update progress

number:
  - platform: ld2410s
    max_distance:
      name: Max detect distance
    min_distance:
      name: Min detect distance
    no_delay:
      name: No detect report delay
    status_reporting_frequency:
      name: Status reporting frequency
    distance_reporting_frequency:
      name: Distance reporting frequency

button:
  - platform: ld2410s
    enable_config:
      name: Enable config mode
    disable_config:
      name: Disable config mode
    apply_config:
      name: Apply config changes
    auto_threshold:
      name: Start auto threshold update

select:
  - platform: ld2410s
    response_speed:
      name: Response speed

text_sensor:
  - platform: ld2410s
    fw_version:
      name: Firmware version
